dist: trusty
os:
- linux
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
  sonarcloud:
    organization: mmasztalerczuk
    token:
      secure: BuCG1F8ji7AUc0rghRWxh3D7Ea+JfsvG9fj2Wi55rYf58lZk7evRaJ6mEMEJmW9axhtIUy05gUFSk0OzVfbHfMchxFc+KkPe0K0IyM62gfMX+q1uT5PgRwvrmGMa1YWSJhxCA2PDY0FxBBj5A176nbMWwn4+ERv45IZ+xJizmOC7r8xY+v2eG3LjXoDoW5kgSvTaOiSEycY3RRKcWY8t2dDGojnNIGvZpKBN9t9mgNnZlvPJBSBfF6/JsfpbD+UcFnkYF0q/aa/Al7DFXppI/wIfbr4I7actf09TlrgmDfdZ4lnoyv++oWQW+rYXIBeKByweQoPwf9jM67KMRKqk/YIfmCxnGGtIGrpUMrPJV17h8eAoXigItjqQHkLMUZBziHnYTrDV5f7k8IS8Bq+YH8QtSJXSmqpyCH10ECDqME7xcdY9nfrbSkngpK2TqF/dObY/nft04MiW9jy8sC9QGEnR2hUDQB1Jmad726xJ9iQRrtONRxPxsjnsqN1pInCOx6macHzDZNrfylw6orRVNytT72n8rkepy6BSrcfdgUE+KNh1cQqmZek6oNovxpKL9mopBgMZRsFDhuUXFwZw9+vytA1m7rZVSfXO0c1ZFLDtF2VurfBLqrc5sf3g7+3owW6ZNTiqRS0UVGGe7CbrtOE+80h79DeK2uPkgINgEys=
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- "./flutter/bin/flutter doctor"
- cp .env_example .env
- gem install coveralls-lcov
script:
- "./flutter/bin/flutter test --coverage"
- sonar-scanner
after_success:
- coveralls-lcov coverage/lcov.info
cache:
  directories:
  - "$HOME/.pub-cache"
